import { FaZhihu,
         FaLaughSquint,
         FaLaughWink,
         FaPizzaSlice,
         FaSortNumericDownAlt,
         FaSortNumericDown,
         FaSortNumericUpAlt,
         FaSortNumericUp,
         FaSortAlphaDownAlt,
         FaSortAlphaDown,
         FaSortAlphaUpAlt,
         FaSortAlphaUp,
         FaSortAmountDownAlt,
         FaSortAmountDown,
         FaSortAmountUpAlt,
         FaSortAmountUp,
         FaThermometerEmpty,
         FaThermometerFull,
         FaThermometerHalf,
         FaThermometerQuarter,
         FaThermometerThreeQuarters,
         FaWifi,
         FaRegCheckCircle,
         FaRegCheckSquare,
         FaRegEnvelopeOpen,
         FaRegEnvelope,
         FaRegGrimace,
         FaRegThumbsDown,
         FaRegThumbsUp,
         FaRegArrowAltCircleDown,
         FaRegArrowAltCircleLeft,
         FaRegArrowAltCircleRight,
         FaRegArrowAltCircleUp,
         FaRegCalendarCheck,
         FaRegCalendarMinus,
         FaRegCalendarPlus,
         FaRegCalendarTimes,
         FaRegCalendar,
         FaRegCaretSquareDown,
         FaRegCaretSquareLeft,
         FaRegCaretSquareRight,
         FaRegCaretSquareUp } from 'react-icons/fa'

export const faIcons = {
    1: <FaZhihu />,
    2: <FaLaughSquint />,
    3: <FaLaughWink />,
    4: <FaPizzaSlice />,
    5: <FaSortNumericDownAlt />,
    6: <FaSortNumericDown />,
    7: <FaSortNumericUpAlt />,
    8: <FaSortNumericUp />,
    9: <FaSortAlphaDownAlt />,
    10: <FaSortAlphaDown />,
    11: <FaSortAlphaUpAlt />,
    12: <FaSortAlphaUp />,
    13: <FaSortAmountDownAlt />,
    14: <FaSortAmountDown />,
    15: <FaSortAmountUpAlt />,
    16: <FaSortAmountUp />,
    17: <FaThermometerEmpty />,
    18: <FaThermometerFull />,
    19: <FaThermometerHalf />,
    20: <FaThermometerQuarter />,
    21: <FaThermometerThreeQuarters />,
    22: <FaWifi />,
    23: <FaRegCheckCircle />,
    24: <FaRegCheckSquare />,
    25: <FaRegEnvelopeOpen />,
    26: <FaRegEnvelope />,
    27: <FaRegGrimace />,
    28: <FaRegThumbsDown />,
    29: <FaRegThumbsUp />,
    30: <FaRegArrowAltCircleDown />,
    31: <FaRegArrowAltCircleLeft />,
    32: <FaRegArrowAltCircleRight />,
    33: <FaRegArrowAltCircleUp />,
    34: <FaRegCalendarCheck />,
    35: <FaRegCalendarMinus />,
    36: <FaRegCalendarPlus />,
    37: <FaRegCalendarTimes />,
    38: <FaRegCalendar />,
    39: <FaRegCaretSquareDown />,
    40: <FaRegCaretSquareLeft />,
    41: <FaRegCaretSquareRight />,
    42: <FaRegCaretSquareUp />
};

export default faIcons;